fix: Format session duration in human-readable form
Teemu/pytest-sugar pull request #265
Opened 2023-01-17 13:41 UTC by last-partizan

Hi, this PR changes output format for long running tests, to include not only seconds, but also minutes (just like default pytest).

2023-01-17 14:33 UTC, auvipy approved these changes

2023-04-03 06:09 UTC, justinmayer approved these changes

2023-04-03 07:49 UTC, auvipy requested changes

2023-04-03 07:49 UTC, auvipy commented on pytest_sugar.py
> +        print(f"\nResults ({format_session_duration(session_duration)}):")
should we get some relevant unit tests for this change?

2023-04-03 12:21 UTC, last-partizan commented on pytest_sugar.py
> +        print(f"\nResults ({format_session_duration(session_duration)}):")
I don't think that's neccessary only for format change.

I'ts very unlikely to break something here, because we're using format_session_duration from pytest itself.

2023-04-10 09:30 UTC, justinmayer commented on pytest_sugar.py
> +        print(f"\nResults ({format_session_duration(session_duration)}):")
I tested this and didn't notice any change in behavior. I haven't tried it on long-running tests, since I don't interact with test suites that take minutes to complete, but presumably @last-partizan has already done that. Let's ship this and take any corrective action if and when the need arises.

2023-04-10 09:30 UTC, merged