Clarify license as BSD 3-Clause License
Teemu/pytest-sugar pull request #285
Opened 2024-06-20 19:34 UTC by justinmayer

I followed the process for [adding a license to an existing repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository), copied and pasted the license that GitHub generates for the [BSD 3-Clause License](https://opensource.org/license/bsd-3-clause) type into the existing `LICENSE` file.

Other than the removal of the "All rights reserved" line, the rest should mostly be formatting changes.

Resolves #284

2024-06-20 19:50 UTC, Teemu requested changes
Sorry to be pedantic but this includes changes that are not just formatting.

"IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE" turns into "IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE"

2024-06-20 20:12 UTC, justinmayer commented
No need to be sorry — I don’t think you are being pedantic.

But now it is my turn to actually be pedantic: I said that the rest should _mostly_ be formatting changes. 😉 

 I am aware of this other, very minor addition. An addition that was not made by me, mind you — all the changes here were entirely copy-pasted from GitHub's license generation tool, as noted in the PR description.

Moreover, the text in this PR is exactly — verbatim — what appears in the [BSD 3-Clause License](https://opensource.org/license/bsd-3-clause).

Finally, wouldn’t we _want_ to extend the same release from liability to folks who graciously volunteer to contribute to the project?

2024-11-14 12:52 UTC, justinmayer commented
Hey Teemu. Is it okay if we proceed and merge this PR?

2024-12-28 10:26 UTC, auvipy approved these changes

2024-12-28 10:27 UTC, merged

2024-12-28 10:28 UTC, auvipy commented
Merging the change as it reflects the current maintainers/contributors as well